/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'laptops' : null } |
  { 'headphones' : null } |
  { 'kitchen' : null } |
  { 'smartHome' : null } |
  { 'fitness' : null } |
  { 'fashion' : null };
export interface Product {
  'id' : bigint,
  'title' : string,
  'originalPrice' : [] | [number],
  'description' : string,
  'affiliateUrl' : string,
  'isActive' : boolean,
  'imageUrl' : string,
  'isFeatured' : boolean,
  'category' : string,
  'badge' : [] | [string],
  'rating' : number,
  'price' : number,
  'reviewCount' : bigint,
  'isTrending' : boolean,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<
    [
      string,
      string,
      number,
      [] | [number],
      string,
      string,
      Category,
      [] | [string],
      number,
      bigint,
      boolean,
      boolean,
    ],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'getTrendingProducts' : ActorMethod<[], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'productExists' : ActorMethod<[bigint], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'seedData' : ActorMethod<[], undefined>,
  'updateProduct' : ActorMethod<
    [
      bigint,
      string,
      string,
      number,
      [] | [number],
      string,
      string,
      Category,
      [] | [string],
      number,
      bigint,
      boolean,
      boolean,
      boolean,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];